### ISSUE TITLE
Argument '--file_name_fields' not required

### ISSUE THREAD

**Issue by ljsalvatierra** [PythonSanSebastian/docstamp#1]
Traceback (most recent call last):
  File "/home/ljsalvatierra/virtualenvs/docstamp/bin/docstamp", line 4, in <module>
    __import__('pkg_resources').run_script('docstamp==0.2.4', 'docstamp')
  File "/home/ljsalvatierra/virtualenvs/docstamp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/ljsalvatierra/virtualenvs/docstamp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/home/ljsalvatierra/virtualenvs/docstamp/local/lib/python2.7/site-packages/docstamp-0.2.4-py2.7.egg/EGG-INFO/scripts/docstamp", line 169, in <module>
    
TypeError: object of type 'NoneType' has no len()

-----------------------------
line 169: "if not len(file_name_fields):"

**Comment by alexsavio** [comment]
Could you check this?
