### ISSUE TITLE
Very weird error

### ISSUE THREAD

**Issue by ljsalvatierra** [PythonSanSebastian/docstamp#4]
ERROR:docstamp.template:Error saving <class 'docstamp.template.SVGDocument'> file in /tmp/tmpQKrhjs.svg
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/docstamp/template.py", line 155, in save_content
    f.write(self.file_content_)#.encode('utf8'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 9637: ordinal not in range(128)
ERROR:__main__:Error creating folder/plantilla_test_0.pdf for {u'a': u'a', u'c': u'c', u'b': u'b'}.
Traceback (most recent call last):
  File "/home/ljsalvatierra/virtualenvs/docstamp/local/lib/python2.7/site-packages/docstamp-0.2.4-py2.7.egg/EGG-INFO/scripts/docstamp", line 245, in <module>
  File "build/bdist.linux-x86_64/egg/docstamp/template.py", line 213, in render
    self.save_content(temp.name)
  File "build/bdist.linux-x86_64/egg/docstamp/template.py", line 155, in save_content
    f.write(self.file_content_)#.encode('utf8'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 9637: ordinal not in range(128)

**Comment by alexsavio** [comment]
Typical encoding error. Because you are using Python 2.7.
We could add the string conversion functions from https://github.com/Neurita/boyle/blob/master/boyle/utils/strings.py#L204

**Comment by alexsavio** [comment]
I'm closing this as it is related with #2
